#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=40 \
                 blur_radius=0 \
                 position=top \
                 sticky=off \
                 padding_left=10 \
                 padding_right=10 \
                 color=$BAR_COLOR

sketchybar --add event aerospace_workspace_change

##### Changing Defaults #####
sketchybar --default icon.font="BlexMono Nerd Font:Regular:15.5" \
                     icon.color=$WHITE \
                     background.color=$ITEM_BG_COLOR \
                     label.font="BlexMono Nerd Font:Regular:15.5" \
                     label.color=$WHITE \
                     padding_left=5 \
                     padding_right=5 \
                     label.padding_left=5 \
                     label.padding_right=5 \
                     icon.padding_left=5 \
                     icon.padding_right=5

# -- Left Side Items --
source $ITEM_DIR/workspace.sh

# -- Right Side Items --
source $ITEM_DIR/clock.sh
source $ITEM_DIR/battery.sh

##### Finalizing Setup #####
sketchybar --update
